<?php
/**
 * Anything generated by code that is gone is not a cache — it is a memory of a
 * different program.
 *
 * ⭐⭐ Caught on his live site twice in one evening. The Optimized pillar caches
 * for an hour, and nothing noticed when the code that produced it was replaced:
 * he uploaded a build with a corrected count, reloaded, and read the OLD number
 * back — "75 graded · 86 being read again", computed by code no longer on the
 * site. The same shape had already shown a card reading "0 graded" beside a
 * perfectly healthy content list.
 *
 * Content changes bust these caches. A schema migration busts them. A plugin
 * UPDATE did neither.
 *
 * @package Agentimus\Tests
 */

namespace Agentimus\Tests;

use Agentimus\Cache;
use PHPUnit\Framework\TestCase;

final class CacheVersionTest extends TestCase {

	protected function setUp(): void {
		\_af_reset_options();
		// ⚠️ The flush is observed through what it DELETES, not through its action:
		// the unit env's do_action() is a no-op, so an action-based assertion here
		// would pass on a flush that never ran.
		$GLOBALS['_af_transients_on'] = true;
		$GLOBALS['_af_transients']    = array();
	}

	protected function tearDown(): void {
		unset( $GLOBALS['_af_transients'], $GLOBALS['_af_transients_on'] );
	}

	/** Something generated, sitting in the cache. */
	private function warm() {
		set_transient( Cache::OPTIMIZE, array( 'score' => 90 ), 3600 );
		set_transient( Cache::LLMS_TXT, 'the index', 3600 );
	}

	private function cached() {
		return array_keys( $GLOBALS['_af_transients'] );
	}

	/**
	 * ⛔⛔ AN ABSENT RECORD IS AN UPGRADE. No site running an older version has
	 * this option — which is precisely the site with a stale cache — so treating
	 * "never recorded" as "fresh install" made this do nothing on the only case
	 * it existed for. It cost him an upload to find. A genuinely fresh install
	 * has nothing cached, so flushing there costs nothing.
	 */
	public function test_a_site_that_never_recorded_a_version_is_treated_as_an_upgrade() {
		$this->warm();

		Cache::verify_version();

		$this->assertSame( array(), $this->cached(), 'Everything here was generated before this option existed.' );
		$this->assertSame( AGENTIMUS_VERSION, get_option( Cache::BUILT_BY ) );
	}

	public function test_an_update_drops_what_the_previous_version_generated() {
		update_option( Cache::BUILT_BY, '1.37.0' );
		$this->warm();

		Cache::verify_version();

		$this->assertSame( array(), $this->cached(), 'These were built by code that is no longer here.' );
		$this->assertSame( AGENTIMUS_VERSION, get_option( Cache::BUILT_BY ) );
	}

	/** …and only once. A flush on every request would be a treadmill. */
	public function test_it_flushes_once_and_then_stays_quiet() {
		update_option( Cache::BUILT_BY, '1.37.0' );
		Cache::verify_version();

		// The next request rebuilds what it needs; a flush on every one of them
		// would be a treadmill, not a cache.
		$this->warm();
		Cache::verify_version();
		Cache::verify_version();

		$this->assertContains( Cache::OPTIMIZE, $this->cached() );
	}
}
