<?php
/**
 * Fill the gaps — the census. Counts and lists the content whose AI fields are
 * still empty: published pages of the agent-visible types without their own
 * description or topic list, and the images those pages actually use (attached
 * or featured) that have no alt text.
 *
 * These are REAL site-wide counts via direct SQL — deliberately not the
 * Optimize pillar's 25-post sample ({@see \Agentimus\Score}), because a
 * backfill screen that says "14 pages are missing descriptions" must mean all
 * 14, not "14 of the ones we looked at".
 *
 * Gap definition (the gap-only law): a field counts as missing when it has no
 * explicit value — the derived fallbacks (excerpt-based description, taxonomy
 * topics) don't fill a gap, they paper over it.
 *
 * @package Agentimus
 */

namespace Agentimus\Bulk;

use Agentimus\Content;
use Agentimus\Description;
use Agentimus\Topics;

defined( 'ABSPATH' ) || exit;

final class Scanner {

	/** The three fillable fields, in screen order. */
	const FIELDS = array( 'description', 'topics', 'alt' );

	/**
	 * How many items one "run" drafts before the screen stops and says "run again"
	 * — Heera's big-site posture: cap each sitting, chunk the work, stay resumable.
	 * Filterable via `agentimus_bulk_run_cap`.
	 */
	const RUN_CAP = 25;

	/** Items generated per REST request (the client loops these up to the run cap). */
	const BATCH_SIZE = 3;

	/**
	 * The per-run cap, filterable.
	 *
	 * @return int
	 */
	public static function run_cap() {
		/**
		 * Filter how many items one bulk run drafts before stopping ("run again").
		 *
		 * @param int $cap Items per run.
		 */
		return max( 1, (int) apply_filters( 'agentimus_bulk_run_cap', self::RUN_CAP ) );
	}

	/**
	 * Whether a field name is one this feature knows.
	 *
	 * @param string $field Field id.
	 * @return bool
	 */
	public static function valid_field( $field ) {
		return in_array( (string) $field, self::FIELDS, true );
	}

	/**
	 * The census: for each field, how many items are missing it and how many
	 * already have a proposal waiting for review.
	 *
	 * @return array<string,array{enabled:bool,missing:int,proposed:int}>
	 */
	public function counts() {
		$out = array();
		foreach ( self::FIELDS as $field ) {
			$out[ $field ] = array(
				'enabled'  => self::field_enabled( $field ),
				'missing'  => $this->missing_count( $field ),
				'proposed' => $this->proposed_count( $field ),
			);
		}
		return $out;
	}

	/**
	 * Whether a field's underlying feature is on (alt text is core WordPress
	 * data, so it has no toggle to be off).
	 *
	 * @param string $field Field id.
	 * @return bool
	 */
	public static function field_enabled( $field ) {
		if ( 'description' === $field ) {
			return Description::enabled();
		}
		if ( 'topics' === $field ) {
			return Topics::enabled();
		}
		return true;
	}

	/**
	 * The next items missing a field, most recently modified first — the pages an
	 * owner touched last are the ones agents are most likely reading now, so they
	 * get filled first. Items that already hold a proposal are skipped: a paid
	 * draft is never regenerated by "run again".
	 *
	 * @param string $field   Field id.
	 * @param int    $limit   Max IDs.
	 * @param int[]  $exclude IDs to leave out — the client passes the items that already
	 *                        FAILED this run, so a failing item can't be picked (and paid
	 *                        for) again and again by consecutive batches.
	 * @return int[]
	 */
	public function missing_ids( $field, $limit, array $exclude = array() ) {
		global $wpdb;
		$limit = max( 1, min( (int) $limit, self::run_cap() ) );

		$skip = '';
		$ids  = array_values( array_filter( array_map( 'absint', $exclude ) ) );
		if ( ! empty( $ids ) ) {
			$col  = 'alt' === $field ? 'a.ID' : 'p.ID';
			$skip = " AND {$col} NOT IN ( " . implode( ', ', $ids ) . ' )';
		}

		if ( 'alt' === $field ) {
			$sql = $this->alt_sql( 'a.ID' )
				. $this->not_exists_meta( 'a.ID', Proposals::meta_key( 'alt' ) )
				. $skip
				. ' ORDER BY a.post_modified DESC LIMIT %d';
			return array_map( 'intval', (array) $wpdb->get_col( $wpdb->prepare( $sql, $limit ) ) ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared -- built from literals + prepared IN list.
		}

		$sql = $this->post_sql( 'p.ID', $field )
			. $this->not_exists_meta( 'p.ID', Proposals::meta_key( $field ) )
			. $skip
			. ' ORDER BY p.post_modified DESC LIMIT %d';
		return array_map( 'intval', (array) $wpdb->get_col( $wpdb->prepare( $sql, $limit ) ) ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared -- built from literals + prepared IN list.
	}

	/**
	 * How many items are missing a field, site-wide.
	 *
	 * @param string $field Field id.
	 * @return int
	 */
	public function missing_count( $field ) {
		global $wpdb;
		$sql = ( 'alt' === $field ) ? $this->alt_sql( 'COUNT(*)' ) : $this->post_sql( 'COUNT(*)', $field );
		return (int) $wpdb->get_var( $sql ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared -- built from literals + prepared IN list.
	}

	/**
	 * How many proposals of a field are waiting for review.
	 *
	 * @param string $field Field id.
	 * @return int
	 */
	public function proposed_count( $field ) {
		global $wpdb;
		return (int) $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM {$wpdb->postmeta} WHERE meta_key = %s",
				Proposals::meta_key( $field )
			)
		);
	}

	/**
	 * The post IDs currently holding a proposal for a field, newest post first —
	 * what the review list pages through.
	 *
	 * @param string $field Field id.
	 * @return int[]
	 */
	public function proposed_ids( $field ) {
		global $wpdb;
		return array_map(
			'intval',
			(array) $wpdb->get_col(
				$wpdb->prepare(
					"SELECT pm.post_id FROM {$wpdb->postmeta} pm JOIN {$wpdb->posts} p ON p.ID = pm.post_id
					 WHERE pm.meta_key = %s ORDER BY p.post_modified DESC",
					Proposals::meta_key( $field )
				)
			)
		);
	}

	/* ---------------------------------------------------------------------- *
	 *  SQL builders
	 * ---------------------------------------------------------------------- */

	/**
	 * Base query for posts missing an explicit description/topics value.
	 *
	 * @param string $select Select expression.
	 * @param string $field  'description' or 'topics'.
	 * @return string
	 */
	private function post_sql( $select, $field ) {
		global $wpdb;
		$key = 'topics' === $field ? Topics::META_TOPICS : Description::META;

		// Present-but-empty counts as missing: '' for the description, and an empty
		// serialized array for the topics list (its meta is a registered array).
		$empty = 'topics' === $field ? "('', 'a:0:{}')" : "('')";

		return "SELECT {$select} FROM {$wpdb->posts} p
			WHERE p.post_type IN ( " . $this->types_in() . " )
			AND p.post_status = 'publish'
			AND NOT EXISTS (
				SELECT 1 FROM {$wpdb->postmeta} m
				WHERE m.post_id = p.ID AND m.meta_key = '" . esc_sql( $key ) . "' AND m.meta_value NOT IN {$empty}
			)";
	}

	/**
	 * Base query for the images that matter and have no alt text: image
	 * attachments either ATTACHED to a published, agent-visible post or set as
	 * one's FEATURED image. The whole media library is deliberately out of scope
	 * — decorative uploads nobody serves to agents aren't a gap worth paying to
	 * fill.
	 *
	 * @param string $select Select expression.
	 * @return string
	 */
	private function alt_sql( $select ) {
		global $wpdb;
		$in = $this->types_in();

		return "SELECT {$select} FROM {$wpdb->posts} a
			WHERE a.post_type = 'attachment'
			AND a.post_mime_type LIKE 'image/%'
			AND (
				a.post_parent IN ( SELECT p.ID FROM {$wpdb->posts} p WHERE p.post_type IN ( {$in} ) AND p.post_status = 'publish' )
				OR a.ID IN (
					SELECT pm.meta_value FROM {$wpdb->postmeta} pm
					JOIN {$wpdb->posts} p2 ON p2.ID = pm.post_id
					WHERE pm.meta_key = '_thumbnail_id' AND p2.post_type IN ( {$in} ) AND p2.post_status = 'publish'
				)
			)
			AND NOT EXISTS (
				SELECT 1 FROM {$wpdb->postmeta} am
				WHERE am.post_id = a.ID AND am.meta_key = '_wp_attachment_image_alt' AND am.meta_value <> ''
			)";
	}

	/**
	 * "AND NOT EXISTS a meta row with this key" — the shared skip-proposed clause.
	 *
	 * @param string $id_col Column holding the post ID.
	 * @param string $key    Meta key.
	 * @return string
	 */
	private function not_exists_meta( $id_col, $key ) {
		global $wpdb;
		return " AND NOT EXISTS ( SELECT 1 FROM {$wpdb->postmeta} x WHERE x.post_id = {$id_col} AND x.meta_key = '" . esc_sql( $key ) . "' )";
	}

	/**
	 * The agent-visible post types as a quoted SQL IN list.
	 *
	 * @return string
	 */
	private function types_in() {
		$types = array_map(
			static function ( $type ) {
				return "'" . esc_sql( (string) $type ) . "'";
			},
			Content::post_types()
		);
		return implode( ', ', $types );
	}
}
